version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t flask-nebracy .
      - docker tag flask-nebracy:latest $REPO_URI
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPO_URI
      - printf '[{"name":"flask","imageUri":"%s"}]' $REPO_URI > imagedefinitions.json
artifacts:
  files: imagedefinitions.json